-- CreateTable
CREATE TABLE "person" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "owner" TEXT NOT NULL,
    "aluno" TEXT NOT NULL,
    "unidade" TEXT NOT NULL,
    "contrato" TEXT NOT NULL,
    "background" TEXT NOT NULL,
    "classe" TEXT NOT NULL,
    "subclasse" TEXT NOT NULL,
    "tmStatus" TEXT NOT NULL,
    "tmVencimento" TEXT NOT NULL,
    "tmValor" TEXT NOT NULL,
    "ppVencimento" TEXT NOT NULL,
    "ppStatus" TEXT NOT NULL,
    "mdValor" TEXT NOT NULL,
    "mdStatus" TEXT NOT NULL,
    "acStatus" TEXT NOT NULL,
    "acFormato" TEXT NOT NULL,
    "Valor" TEXT NOT NULL,
    "tipoMatricula" TEXT NOT NULL,
    "tipoComissao" TEXT NOT NULL,
    "comissaoValor" TEXT NOT NULL,
    "aprovacaoADM" TEXT NOT NULL,
    "responsavelADM" TEXT NOT NULL,
    "aprovacaoDirecao" TEXT NOT NULL,
    "diretorResponsavel" TEXT NOT NULL,
    "dataAC" TEXT NOT NULL,
    "paDATA" TEXT NOT NULL,
    "inicioContrato" TEXT NOT NULL,
    "fimContrato" TEXT NOT NULL,
    "tel" TEXT NOT NULL,
    "email" TEXT NOT NULL,

    CONSTRAINT "person_pkey" PRIMARY KEY ("id")
);
